workflows: only run codeql analysis on yubico/libfido2
This job will fail on repositories which do not have CodeQL enabled with
the error message

    Error: init action failed: HttpError: repository not enabled for
    code scanning

Instead of generating an error, skip the job if the pipeline runs in
another repository than yubico/libfido2.